name: CI

on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test release-tagger
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
      - name: Run release-tagger
        uses: ./
