name: CI

on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test release-tagger
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
      - name: Run release-tagger
        uses: ./
